name: Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6
      - run: rustup toolchain install stable --profile minimal
      - uses: michaelklishin/rust-build-package-release-action@v3
        id: build
        with:
          command: release
          target: x86_64-unknown-linux-gnu
          archive: 'true'
      - uses: softprops/action-gh-release@v3.0.3
        with:
          files: target/x86_64-unknown-linux-gnu/release/*.tar.gz
